site_name: Shard Tech 4 SDK 

theme: windmill

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting started: gettingstarted.md
  - Reference: reference.md
  - Credits: credits.md
  - License: license.md